### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `mod`
  - `raft`
  - `physics`

  <br>

- **Update Description**

  `Raft mod for simple latern physics.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Added license / contribution badges

- Added quicklinks

- Extended development instructions

- Referenced links

- Formatted code / manifest

  *please check*

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/raft-lantern-physics-mod

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@FZ-Applications Please review this PR

**Review by FZ-Applications — CHANGES_REQUESTED** [review]
Thank you for the effort.
The tips and the changes to the readme file are very appreciated.
On the other hand, it's unnecessary to reformat the modinfo.json, as I used the example mod as a template. (https://api.raftmodding.com/modding-tutorials/how-to-create-a-mod-project/the-modinfo.json-file)
Also, the reformatting of the code is debateable. It's very much a matter of personal preference, but I don't like bloat the code unnecessary with lots of empty lines and a switch for 2 conditions.
I will only approve the PR for the README.md file.

**Comment by ElectronicsArchiver** [comment]
> On the other hand, it's unnecessary to reformat the modinfo.json, as I used the example mod as a template.

How does using the example make formatting it unnecessary?

> Also, the reformatting of the code is debateable. It's very much a matter of personal preference, but I don't like bloat the code unnecessary with lots of empty lines and a switch for 2 conditions.

Spacing your code doesn't make it slower nor does it increase the 
filesize in any meaningful large amount to be concerned about it?

If you cared about it, wouldn't you use a build setup with a minimizer?

> I will only approve the PR for the README.md file.

Sure, just wanna ask ^ first~

**Comment by FZ-Applications** [comment]
> How does using the example make formatting it unnecessary?
Most mods keep the order of the modinfo.json file as it is in the template. So why should I reinvent the wheel?

> Spacing your code doesn't make it slower nor does it increase the filesize in any meaningful large amount to be concerned about it?
I know it doesn't make it any slower, but it's mostly just personal preference and you have to scroll less.

**Comment by ElectronicsArchiver** [comment]
> Most mods keep the order of the modinfo.json file as it is in the template. So why should I reinvent the wheel?

It's just a config file and it's just formatting,
there is no reinventing anything to begin with~

> I know it doesn't make it any slower, but it's mostly just personal preference and you have to scroll less.

I see~

I will adjust the PR then.

**Pull request merged**
